apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
spec:
  acme:
    # Dev Let's Encrypt server (higher rate limits for testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: engineering.abhishek17@gmail.com
    privateKeySecretRef:
      name: letsencrypt-dev-account-key
    solvers:
      - dns01:
          webhook:
            solverName: linode
            groupName: acme.slicen.me
            config:
              apiTokenSecretRef:
                name: admin-cred-token
                key: token
