apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linode-csi-driver
  namespace: kube-system
spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: linode-blockstorage-csi-driver
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: linode-csi
        namespace: flux-system
      interval: 1h

  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    secretRef:
      name: ccm-token
      apiTokenRef: token
      regionRef: region
