---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-extra-permissions-role
rules:
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redisreplications
  - redissentinels
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-extra-permissions-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-extra-permissions-role
subjects:
- kind: ServiceAccount
  name: redis-operator
  namespace: persistence
---