apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser-secret
    namespace: persistence
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:QJZieIHrbu8=,iv:bK9zp7FKilgRa6xQFV4kPkNGVFOSypsSf9UOLiAzkmk=,tag:vC4dXnzwRDNAvyqK6UnZxg==,type:str]
    password: ENC[AES256_GCM,data:wIZ1SQBvJJ7Z5SjFQ/s30Vmh1dE=,iv:m4K/pWfZEG1y9IcqvMC7vj3GRbYerslEdVZgNlPTv1I=,tag:4wKtG66gdVsr7aJKDZKwDQ==,type:str]
sops:
    age:
        - recipient: age1nhfyaxttusg65xyyw52pjeve2enmsjmg8akcmehwf40c37nqnu7qqk690n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RlhuSnJ5bUMyeEhIdE5y
            Y3picVFBblpiZEdTclpoNHRveEo5eGdOb2pRCjNFaUFSRndyd01aMy95bU8wU3Vj
            NFR4VWhBLzlPeDdwT21tZ2hFT2duNGMKLS0tIDBaWk5HTWFwOG9lNW04bU1MVjBF
            alUrY2lrSDdJL3hzVVVZSG5naUtUU00K2Tzqc7FeIjhEG+kSv9wjCdZHqf5rTuuR
            RiRjtIt4T10RM5A/6bsJ8ulQpkPzleTblbLQDxV0CeneRcf04Q8OXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T05:53:34Z"
    mac: ENC[AES256_GCM,data:vsM8pBIwm63B5R4OwCsg+06GeQDXyqhujDzsoqv+9+yjz9+FO1UoE1ZCpqg3CO4oU4lCgDOfhhbQOmH4XwcytWo+CUqhSHFW3q1jQ+Uwyetimo6SiLhhG7JMUjLBO6Jc7xvRZFuUnzvpLSBvuaLMWFXi/vVwxgPxxxzTdQWSo8Q=,iv:n4xWfhgP5CoCm7sXz4dBXKMs4WrIBu/Mtu9FvdIxCFs=,tag:KUlNpSSZkTwsOOhI502xbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
