apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 1h
  timeout: 30m
  chart:
    spec:
      chart: nextcloud
      version: 8.9.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 1h

  values:
    replicaCount: 1

    image:
      flavor: fpm
      tag: stable-fpm

    httpRoute:
      enabled: true
      hostnames:
        - "hub.sigdep.cloud"
      parentRefs:
        - name: external-gateway
          namespace: ingress
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: "/"
          filters:
            - type: ExtensionRef
              extensionRef:
                group: traefik.io
                kind: Middleware
                name: nextcloud-redirects

    phpClientHttpsFix:
      enabled: true
      protocol: https

    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      host: "postgres-pooler.persistence.svc.cluster.local:5432"
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-db-secret
        usernameKey: username
        passwordKey: password

    externalRedis:
      enabled: true
      host: "redis-standalone-cluster.persistence.svc.cluster.local"
      port: "6379"
      existingSecret:
        enabled: true
        secretName: redis-user-secret
        passwordKey: password

    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: linode-block-storage-retain
      nextcloudData:
        enabled: true
        size: 20Gi
        accessMode: ReadWriteOnce
        storageClass: linode-block-storage-retain

    service:
      type: ClusterIP
      port: 8080
      sessionAffinity: ClientIP

    rbac:
      enabled: true

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1.5
        memory: 1536Mi

    nextcloud:
      host: hub.sigdep.cloud
      existingSecret:
        enabled: true
        secretName: nextcloud-admin-secret
        usernameKey: username
        passwordKey: password
        tokenKey: ""
        smtpUsernameKey: smtpUsername
        smtpPasswordKey: smtpPassword
        smtpHostKey: smtpHost
      trustedDomains:
        - hub.sigdep.cloud
        - nextcloud.nextcloud.svc.cluster.local
        - localhost
      objectStore:
        s3:
          enabled: true
          host: us-ord-1.linodeobjects.com
          bucket: sigdep-nextcloud-primary
          region: us-ord-1
          port: "443"
          ssl: true
          usePathStyle: false
          autoCreate: false
          existingSecret: nextcloud-s3-primary-secret
          secretKeys:
            host: host
            accessKey: accessKey
            secretKey: secretKey
            bucket: bucket

      phpConfigs:
        upload_limit.ini: |
          upload_max_filesize = 10G
          post_max_size = 10G
          memory_limit = 1G
        www.conf: |
          [www]
          pm = dynamic
          pm.max_children = 40
          pm.start_servers = 10
          pm.min_spare_servers = 10
          pm.max_spare_servers = 25
          pm.max_requests = 500
        opcache.ini: |
          opcache.enable=1
          opcache.interned_strings_buffer=16
          opcache.max_accelerated_files=10000
          opcache.memory_consumption=128
          opcache.save_comments=1
          opcache.revalidate_freq=1

      defaultConfigs:
        .htaccess: true
        redis.config.php: true
        s3.config.php: true
        reverse-proxy.config.php: true
        apcu.config.php: true
        apps.config.php: false
        imaginary.config.php: false

      configs:
        tuning.config.php: |-
          <?php
          $CONFIG = array (
            'check_data_directory_permissions' => false,
            'overwriteprotocol' => 'https',
            'objectstore_multipart_threshold' => 52428800,
            'preview_max_x' => 1024,
            'preview_max_y' => 1024,
            'image_optim_quality' => 60,
            'enable_previews' => true,
            'enabledPreviewProviders' => array (
              'OC\Preview\PNG',
              'OC\Preview\JPEG',
              'OC\Preview\GIF',
              'OC\Preview\BMP',
              'OC\Preview\MarkDown',
              'OC\Preview\MP3',
              'OC\Preview\TXT',
              'OC\Preview\Illustrator',
              'OC\Preview\Movie',
              'OC\Preview\Photoshop',
              'OC\Preview\PDF',
            ),
          );

        apps.config.php: |-
          <?php
          $CONFIG = array (
            'memories.exiftool_no_local' => true,
            'memories.vod.ffmpeg' => '/usr/bin/ffmpeg',
            'memories.vod.ffprobe' => '/usr/bin/ffprobe',
            'talk_use_reflection' => true,
          );

        office.config.php: |-
          <?php
          $CONFIG = array (
            'allow_user_to_change_display_name' => false,
            'collabora_group' => 'admin',
          );

        imaginary.config.php: |-
          <?php
          $CONFIG = array (
            'preview_imaginary_url' => 'http://nextcloud-imaginary:9000',
          );

        oidc.config.php: |-
          <?php
          $CONFIG = array (
            'oidc_login_provider_url' => getenv('AUTH0_DOMAIN'),
            'oidc_login_client_id' => getenv('AUTH0_CLIENT_ID'),
            'oidc_login_client_secret' => getenv('AUTH0_CLIENT_SECRET'),
            'oidc_login_auto_create_users' => true,
            'oidc_login_link_existing_users' => true,
            'oidc_login_login_button_text' => 'Login to SigDep with Auth0',
            'oidc_login_auto_redirect' => false,
            'oidc_login_end_session_redirect' => true,
            'oidc_login_scope' => 'openid profile email',
            'oidc_login_attributes' => array (
              'id' => 'email',
              'name' => 'name',
              'mail' => 'email',
            ),
          );

      extraInitContainers:
        - name: init-redis-session-ini
          image: busybox
          securityContext:
            runAsUser: 33
            runAsGroup: 33
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          command: ['touch', '/usr/local/etc/php/conf.d/redis-session.ini']
          volumeMounts:
            - name: nextcloud-redis-session-ini
              mountPath: "/usr/local/etc/php/conf.d"

      extraVolumes:
        - name: nextcloud-redis-session-ini
          emptyDir: {}

      extraVolumeMounts:
        - name: nextcloud-redis-session-ini
          mountPath: "/usr/local/etc/php/conf.d/redis-session.ini"
          subPath: redis-session.ini

      extraEnv:
        - name: AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              name: nextcloud-auth0-secret
              key: domain
        - name: AUTH0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: nextcloud-auth0-secret
              key: clientId
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: nextcloud-auth0-secret
              key: clientSecret

      securityContext:
        runAsUser: 33
        runAsGroup: 33
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false

      podSecurityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
        fsGroupChangePolicy: "Always"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

    nginx:
      enabled: true
      image:
        repository: nginxinc/nginx-unprivileged
        tag: alpine
      config:
        default: true
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi

    cronjob:
      enabled: true
      type: cronjob
      cronjob:
        schedule: "*/5 * * * *"
        securityContext:
          runAsUser: 33
          runAsGroup: 33
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
        affinity:
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - nextcloud
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - app
                topologyKey: kubernetes.io/hostname

    imaginary:
      enabled: true
      replicaCount: 1
      image:
        tag: 1.2.4
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 512Mi
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      podSecurityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
