apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ccm-linode
  namespace: kube-system
spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: ccm-linode
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ccm-linode
        namespace: flux-system
      interval: 1h

  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    secretRef:
      name: ccm-token
      apiTokenRef: token
      regionRef: region
    image:
      pullPolicy: IfNotPresent
    logVerbosity: 3
