apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: metrics-server
      version: 3.13.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      interval: 1h

  values:
    replicas: 1
    apiService:
      insecureSkipTLSVerify: false
    tls:
      type: cert-manager
    args:
      - --kubelet-insecure-tls
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        memory: 200Mi
